package com.jsoko.events;

public enum Event {
    // Game events
    GAME_GROUPS_SCREEN_ENTERED,
    GAME_LEVELS_SCREEN_ENTERED,

    GAME_GROUP_SELECTED,
    GAME_LEVEL_SELECTED,

    GAME_GROUPS_DATA,
    GAME_LEVELS_DATA,

    GAME_OUT_OF_UNDOS,
    GAME_UNDOS_AVAILABLE,
    GAME_SAVE_PROGRESS,
    GAME_SOLVE,
    GAME_SKIP_SOLVE,
    GAME_BACK,

    GAME_MOVE_LEFT,
    GAME_MOVE_RIGHT,
    GAME_MOVE_UP,
    GAME_MOVE_DOWN,
    GAME_MOVE_UNDO,
    GAME_RESTART_LEVEL,
    GAME_LEVEL_COMPLETED,

    SOLVER_MOVE_LEFT,
    SOLVER_MOVE_RIGHT,
    SOLVER_MOVE_UP,
    SOLVER_MOVE_DOWN,

    GAME_SUMMARY_SCREEN_EXIT,

    // Dialog events
    GAME_EXIT_DIALOG_REQUEST,
    GAME_EXIT_DIALOG_SHOW,
    GAME_RESTART_DIALOG_REQUEST,
    GAME_RESTART_DIALOG_SHOW,
    GAME_SOLVE_DIALOG_REQUEST,
    GAME_SOLVE_DIALOG_SHOW,

}
